import type { Metadata } from "next";
import { Merriweather, Plus_Jakarta_Sans } from "next/font/google";
import "./globals.css";
import ReactQueryProvider from "./providers/react-query-provider";
import ConditionalWrapper from "@/components/layout/ConditionalWrapper";
import localFont from 'next/font/local'

const merriweather = Merriweather({
  weight: ["300", "400", "700", "900"],
  subsets: ["latin"],
  variable: "--font-merriweather",
});

const plusJakartaSans = Plus_Jakarta_Sans({
  weight: ["400", "500", "600", "700"],
  subsets: ["latin"],
  variable: "--font-plus-jakarta-sans",
});
const myFont = localFont({
  src: '../public/helvetica-neue-5/HelveticaNeueRoman.otf',
  variable: '--font-helvetical',
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${merriweather.variable} ${myFont.variable} ${plusJakartaSans.variable} antialiased font-body`}
      >
        <ReactQueryProvider>
          <ConditionalWrapper>{children}</ConditionalWrapper>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
