import type { Metadata } from "next";
import { Merriweather } from "next/font/google";
import "./globals.css";
import ReactQueryProvider from "./providers/react-query-provider";
import Navbar from "@/components/landing/Navbar";
import Footer from "@/components/landing/Footer";
import localFont from 'next/font/local'

const merriweather = Merriweather({
  weight: ["300", "400", "700", "900"],
  subsets: ["latin"],
  variable: "--font-merriweather",
});
const myFont = localFont({
  src: '../public/helvetica-neue-5/HelveticaNeueRoman.otf',
  variable: '--font-helvetical',
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${merriweather.variable} ${myFont.variable} antialiased font-body`}
       
      >
        <ReactQueryProvider>
          <Navbar />
          <div className="py-20">{children}</div>
          <Footer />
        </ReactQueryProvider>
      </body>
    </html>
  );
}
